export const EMAIL_LOGIN = "EMAIL_LOGIN";


export const CONTACT_CREATE = "CONTACT_CREATE";
export const CONTACT_LIST = "CONTACT_LIST";
export const CONTACT_EDIT = "CONTACT_EDIT";
export const CONTACT_VIEW = "CONTACT_VIEW";
export const CONTACT_DELETE = "CONTACT_DELETE";